version: '2'

services:
  insurance-ca:
    container_name: insurance-ca
    extends:
      file: ./ca-base.yaml
      service: ca-base
    image: insurance-ca
    ports:
    - 7054:7054

  doctor-ca:
    container_name: doctor-ca
    extends:
      file: ./ca-base.yaml
      service: ca-base
    image: doctor-ca
    ports:
    - 8054:7054

  pharma-ca:
    container_name: pharma-ca
    extends:
      file: ./ca-base.yaml
      service: ca-base
    image: pharma-ca
    ports:
    - 9054:7054

  patient-ca:
    container_name: patient-ca
    extends:
      file: ./ca-base.yaml
      service: ca-base
    image: patient-ca
    ports:
    - 10054:7054

  orderer0:
    container_name: orderer0
    image: orderer
    environment:
    - ORDERER_GENERAL_LOGLEVEL=debug
    - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
    - ORDERER_GENERAL_GENESISMETHOD=file
    - ORDERER_GENERAL_GENESISFILE=/orderer/crypto/genesis.block
    - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
    - ORDERER_GENERAL_LOCALMSPDIR=/orderer/crypto/msp
    - ORDERER_GENERAL_TLS_ENABLED=true
    - ORDERER_GENERAL_TLS_PRIVATEKEY=/orderer/crypto/tls/server.key
    - ORDERER_GENERAL_TLS_CERTIFICATE=/orderer/crypto/tls/server.crt
    - ORDERER_GENERAL_TLS_ROOTCAS=[/orderer/crypto/tls/ca.crt]
    working_dir: /orderer
    command: orderer
    ports:
    - 7050:7050

  insurance-peer:
    container_name: insurance-peer
    extends:
      file: ./peer-base.yaml
      service: peer-base
    image: insurance-peer
    environment:
    - CORE_PEER_ID=insurance-peer
    - CORE_PEER_ADDRESS=insurance-peer:7051
    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=insurance-peer:7051
    - CORE_PEER_LOCALMSPID=InsuranceOrgMSP
    ports:
    - 7051:7051
    - 7053:7053
    depends_on:
    - orderer0

  doctor-peer:
    container_name: doctor-peer
    extends:
      file: ./peer-base.yaml
      service: peer-base
    image: doctor-peer
    environment:
    - CORE_PEER_ID=doctor-peer
    - CORE_PEER_ADDRESS=doctor-peer:7051
    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=doctor-peer:7051
    - CORE_PEER_LOCALMSPID=ShopOrgMSP
    ports:
    - 8051:7051
    - 8053:7053
    depends_on:
    - orderer0
    - insurance-peer

  pharma-peer:
    container_name: pharma-peer
    extends:
      file: ./peer-base.yaml
      service: peer-base
    image: pharma-peer
    environment:
    - CORE_PEER_ID=pharma-peer
    - CORE_PEER_ADDRESS=pharma-peer:7051
    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=pharma-peer:7051
    - CORE_PEER_LOCALMSPID=PharmaOrgMSP
    ports:
    - 9051:7051
    - 9053:7053
    depends_on:
    - orderer0
    - insurance-peer
    - doctor-peer

  patient-peer:
    container_name: patient-peer
    extends:
      file: ./peer-base.yaml
      service: peer-base
    image: patient-peer
    environment:
    - CORE_PEER_ID=patient-peer
    - CORE_PEER_ADDRESS=patient-peer:7051
    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=patient-peer:7051
    - CORE_PEER_LOCALMSPID=PoliceOrgMSP
    ports:
    - 10051:7051
    - 10053:7053
    depends_on:
    - orderer0
    - insurance-peer
    - doctor-peer
    - pharma-peer

  web:
    container_name: web
    image: web
    environment:
    - PORT=3000
    - DOCKER_SOCKET_PATH=/host/var/run/docker.sock
    - DOCKER_CCENV_IMAGE=hyperledger/fabric-ccenv:latest
    ports:
    - 3000:3000
    volumes:
    - /var/run/:/host/var/run/
    depends_on:
    - orderer0
    - insurance-ca
    - insurance-peer
    - doctor-ca
    - doctor-peer
    - pharma-ca
    - pharma-peer
